nameless_games/main/urls.py
from django.urls import path
from . import views


app_name = "main"

#urls para las diferentes partes del proyecto  

urlpatterns = [
	path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),
	path('logout/', views.logoutUser, name="logout"),

	path('', views.IndexView.as_view(), name="home"),
	path('contact/', views.ContactView.as_view(), name="contact"),
	path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
	path('blog/', views.BlogView.as_view(), name="blogs"),
	path('profiles/', views.profiles.as_view(), name="profiles"),
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),

	]

nameless_games/nameless_games/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nameless_games/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

#modelo de skill
class Skill(models.Model):
    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'
    
    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = models.FileField(blank=True, null=True, upload_to="skills")
    is_key_skill = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

#modelo de user profile
class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

#modelo de contacto 
class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'

class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

#modelo de blogs  
class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"
        #se realizo eliminacion de certificate

#modelo de portfolio
class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]
    
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"

nameless_games/main/forms.py
from django import forms
from .models import ContactProfile ,Blog  #, Testimonial 

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Se usaron forms para Creacion de usuarios y para el contacto 

class CreateUserForm(UserCreationForm):
	class meta :
		model = User 
		fields =["username", "email", "pasword1", "pasword2"]

class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)
		

nameless_games/main/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages
from .models import (
		UserProfile,
		Blog,
		Portfolio,
		#Testimonial,
		
	)

from django.views import generic


from . forms import  CreateUserForm , ContactForm #, BlogForm, TestimonialForm

#aqui se hacen un monton de form para el usuario login etc 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect

#se agregan el register page y el login 
def registerPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('main:login')
			

		context = {'form':form}
		return render(request, 'main/register.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect("main:home")
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'main/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('main:login')

class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		#eliminacion de certificate y testimonial
		#testimonials = Testimonial.objects.filter(is_active=True)
		#certificates = Certificate.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		portfolio = Portfolio.objects.filter(is_active=True)
		
		#eliminacion de certificate y testimonial x2
		#context["testimonials"] = testimonials
		#context["certificates"] = certificates
		context["blogs"] = blogs
		context["portfolio"] = portfolio
		return context
#para la parte de contact 
class ContactView(generic.FormView):
	template_name = "main/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Apuesto fue el perro 7.7 hmmp.')
		return super().form_valid(form)

#para la parte de blogs 
class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-detail.html"

#para la parte de portfolios

class profiles(generic.ListView):
	model = UserProfile
	template_name = "main/profiles.html"



class PortfolioView(generic.ListView):
	model = Portfolio
	template_name = "main/portfolio.html"
	paginate_by = 10
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)

class PortfolioDetailView(generic.DetailView):
	model = Portfolio
	template_name = "main/portfolio-detail.html"

nameless_games/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'main:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/WOFF.png' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/WOFF.png' %}">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extend_header%}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'main/partials/messages.html' %}
    {% include 'main/partials/nav.html' %}
    
    {% block content %}
    {% include 'main/partials/footer.html' %}
    {% block extend_footer %}{%endblock%}
    {% endblock %}
  </body>
</html>

nameless_games/main/templates/main/blog-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<!-- Section donde se muestran los blogs con su descripcion etc-->

<section>
  <body style="background-color:rgba(3, 61, 109, 0.856);">
  <div class="innerPageBannerCol ">
    <div class="container" style="background-color:rgba(197, 219, 238, 0.856); ">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">{{object.name|title}}</h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto">
          <div class="authorCol">
            <h4 class="smTitle pb-3">{{object.author|title}}</h4>
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">{{object.timestamp.date}}</h4>
        </div>
   

  <div class="sectionSpaceSm">
    <div class="container">
      
      {{object.body|safe}}
    </div>
    <div class="col-auto ">
      <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Game!!1</a>
</div> 
    </div>
    </div>
  </div>
  
  </section>



<!-- ================================
End Content
================================= -->


{% endblock %}
 <!--================================
End Content
================================= -->
   

nameless_games/main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<!--Pagina del blog donde salen las imagenes de los mismos-->
<section>
  <body style="background-color:rgba(3, 61, 109, 0.856);"></body>
  <div class="innerPageBannerCol">
    <div class="container lightBg">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Catalogo de Juegos</h1>
          </div>
        </div>
  </div>
</section>
<section>
  <div class="bg-dark">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:blog' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}

     </div>
      </div>
    </div>
  </div>
</section>
</body>


<!-- ================================
End Content
================================= -->
{%endblock%} 

nameless_games/main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<!-- Section donde se pide ayuda en causa de errores-->
<section>
  <body style="background-color:rgba(3, 61, 109, 0.856);">
    
      
  <div class="innerPageBannerCol">
    <div class="container" style="background-color:rgba(197, 219, 238, 0.856); "></di>

      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Algun problema?</h1>
          </div>
        </div>
      </div>
    </div>
  </div>

 
    <div class="container"style="background-color:rgba(197, 219, 238, 0.856); "></di>
        <form id="contactForm" method="POST" action="/contact/">
        {% csrf_token %}
            <label for="name">Nombre</label>
            {{form.name}}

            <label for="email">Email</label>
            {{form.email}}

            <label for="subject">cuentans tu problema</label>
            {{form.message}}

            <input class='btn btnPrimary' type="submit" value="Envia tu duda">
        </form>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}
    

nameless_games/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->


<!-- Esta parte se trata de la pgina principal donde sale nuestro avatar entre otros -->
{% block content %}
<!DOCTYPE html>
<body style="background-color:rgba(3, 61, 109, 0.856);">

<html lang="en">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, inital-scale=1.8">
        <title>Nameless Games!</title>
    </head>
    <div class="container-fluid" id="background-head">
                <div class = "rows">
                 <header class="py-5 bg-image-full" style="background-image: url('https://www.enwallpaper.com/wp-content/uploads/2021/02/29-294447-download-undertale-wallpaper-desktop-undertale-waterfall-art.png')">
                    <div class="text-center my-5">
                        <img src="{% static 'images/title3.png' %}" alt="...">
                    </div>
                </header>
            </div>
        </div>

        <section>
            <div class="sectionSpaceSm background-color">
              <div class="container">
                <div class="row pb-3">
                  <div class="col">
                    
                    <h4 class="smText regular text-white">Juegos más Populares!</h4>
                  </div>
                  <div class="col-auto">
                    <a href="{% url 'main:blogs' %}" class="simpleLink text-white">Más</a>
                  </div>
                </div>
                <div class="row g-3">
                {% for b in blogs %}
                {% if b.is_active %}
                  <div class="col-lg-6">
                    <div class="cardStyle1 ">
                      <h4 class="mdTitle cs1Title"><a href="{% url 'main:blog' slug=b.slug %}">{{b.name}}</a></h4>
                      <ul class="cardOptionCol">
                        <li>{{b.timestamp.date}}</li>
                        <li>{{b.author}}</li>
                      </ul>
                      <p>{{b.description}}</p>
                    </div>
                  </div>
                  
               
                  
                          {% endif %}
                          {% endfor %}
                </section>            
<section>
  <div class="sectionSpace">
    <div class="container " style="background-color:rgba(197, 219, 238, 0.856); ">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular text-white">ROMs Disponibles</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'main:portfolios' %}" class="simpleLink text-white">Más</a>
          </div>
        </div>
        {% for p in portfolio %}
        {% if p.is_active %}
        <div class="portfolioCard">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="portfolioImgCol">
                <a href="{% url 'main:portfolio' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
              </div>
            </div>
            <div class="col-md">
              <div class="portfolioContentCol">
                <h4 class="lgTitle"><a href="{% url 'main:portfolio' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="portfolioOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p>{{p.description}}</p>
              </div>
            </div>
          </div>
        </div>
     
         
          {% endif %}
          {% endfor %}
        </section>
          
                    
        
</body>
</html>
{%endblock%} 

nameless_games/main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<!-- Section de inicio de sesion -->
<section>
  <body style="background-color:rgba(3, 61, 109, 0.856);">

    <div class="innerPageBannerCol">
      <div class="container" style="background-color:rgba(197, 219, 238, 0.856); ">
        <div class="row g-4 g-md-3  align-items-center">
          <div class="col-md-6">
            <div class="bannerContent">
              <h1 class="xlTitle pb-md-3">Inicio de sesión</h1>
            </div>
       
    </div>
  </section>
  


<div class="container h-100  lightBg">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>

                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>

                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>

                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                    </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                             <input class="btn bg-info" type="submit" value="Login">
                           </div>
                </form>

            </div>

            {% for message in messages %}
                <p id="messages">{{message}}</p>
            {% endfor %}			
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                   No tienes cuenta? <a href="{% url 'main:register' %}" class="ml-2">Registrate</a>
                </div>
        
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>





</body>



{% endblock %}
<!-- ================================
End Content
================================= -->

nameless_games/main/templates/main/portfolio-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<!-- Section donde se muestran los portfolio con su descripcion etc-->
<section>
  <body style="background-color:rgba(3, 61, 109, 0.856);">
  <div class="innerPageBannerCol">
    <div class="container" style="background-color:rgba(197, 219, 238, 0.856); ">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">{{object.name}}</h1>
          </div>
       
  </div>

  <div class="sectionSpaceSm">
    <div class="container">
      {{object.body|safe}}
    </div>
    <div class="col-auto">
      <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Game!!1</a>
    </div> 
  </div>
</div>
</div>
</div>

</div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}

nameless_games/main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<!-- Section donde se muestran los portfolios-->
<section>
  <body style="background-color:rgba(3, 61, 109, 0.856);">
  <div class="innerPageBannerCol">
    <div class="container"style="background-color:rgba(197, 219, 238, 0.856); ">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Roms famosos!1!</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="bg-dark">
    <div class="container bg">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:portfolio' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{% endblock%}    